void comp_hist_fit_rms_graph_errors() {
   TCanvas *c1 = new TCanvas("graph1","graph1",200,10,700,500);
   TCanvas *c2 = new TCanvas("graph2","graph2",200,10,700,500);
   TCanvas *c3 = new TCanvas("graph3","graph3",200,10,700,500);
   TCanvas *c4 = new TCanvas("graph4","graph4",200,10,700,500);

   c1->SetGrid();
   c2->SetGrid();
   c3->SetGrid();
   c4->SetGrid();

   const Int_t n = 9; // 16

   Float_t energy[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t energyerror[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
    
   Float_t mean[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t meanerror[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t rms[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t rmserror[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
     
   Float_t mean60[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t rms60[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t mean65[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t rms65[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t mean70[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t rms70[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t mean75[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t rms75[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t mean80[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t rms80[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t mean85[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t rms85[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t mean90[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t rms90[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t mean95[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t rms95[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t mean100[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t rms100[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
    
   Float_t mean_mean[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t rms_mean[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t mean_meanerror[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t rms_meanerror[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t mean_sigma[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t rms_sigma[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t mean_sigmaerror[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t rms_sigmaerror[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t mean_chi[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t rms_chi[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
    
   Float_t ratio_hist[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t ratio_error_stat_hist[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t ratio_error_sys_hist[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t ratio_error_hist[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t resolution_hist[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t resolution_error_stat_hist[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t resolution_error_sys_hist[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t resolution_error_hist[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
    
   Float_t ratio60[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t ratio_error_stat60[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t ratio_error_sys60[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t ratio_error60[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t resolution60[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t resolution_error_stat60[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t resolution_error_sys60[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t resolution_error60[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   
   Float_t ratio65[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t ratio_error_stat65[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t ratio_error_sys65[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t ratio_error65[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t resolution65[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t resolution_error_stat65[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t resolution_error_sys65[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t resolution_error65[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   
   Float_t ratio70[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t ratio_error_stat70[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t ratio_error_sys70[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t ratio_error70[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t resolution70[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t resolution_error_stat70[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t resolution_error_sys70[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t resolution_error70[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   
   Float_t ratio75[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t ratio_error_stat75[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t ratio_error_sys75[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t ratio_error75[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t resolution75[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t resolution_error_stat75[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t resolution_error_sys75[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t resolution_error75[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   
   Float_t ratio80[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t ratio_error_stat80[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t ratio_error_sys80[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t ratio_error80[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t resolution80[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t resolution_error_stat80[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t resolution_error_sys80[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t resolution_error80[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   
   Float_t ratio85[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t ratio_error_stat85[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t ratio_error_sys85[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t ratio_error85[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t resolution85[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t resolution_error_stat85[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t resolution_error_sys85[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t resolution_error85[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   
   Float_t ratio90[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t ratio_error_stat90[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t ratio_error_sys90[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t ratio_error90[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t resolution90[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t resolution_error_stat90[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t resolution_error_sys90[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t resolution_error90[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   
   Float_t ratio95[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t ratio_error_stat95[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t ratio_error_sys95[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t ratio_error95[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t resolution95[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t resolution_error_stat95[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t resolution_error_sys95[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t resolution_error95[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   
   Float_t ratio100[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t ratio_error_stat100[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t ratio_error_sys100[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t ratio_error100[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t resolution100[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t resolution_error_stat100[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t resolution_error_sys100[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t resolution_error100[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   
   Float_t linearity_error[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t absolute_error[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t ratio[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t ratio_error_stat[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t ratio_error_sys[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t ratio_error[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t resolution[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t resolution_error_stat[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t resolution_error_sys[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t resolution_error[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
    
   Float_t mean_mean2[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t rms_mean2[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t mean_meanerror2[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t rms_meanerror2[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t mean_sigma2[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t rms_sigma2[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t mean_sigmaerror2[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t rms_sigmaerror2[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t mean_chi2[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t rms_chi2[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
    
   Float_t linearity_error2[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t absolute_error2[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t ratio2[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t ratio_error_stat2[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t ratio_error_sys2[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t ratio_error2[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t resolution2[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t resolution_error_stat2[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t resolution_error_sys2[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   Float_t resolution_error2[n] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };

   FILE *file1 = fopen("new_1out_data.txt", "r");
   if ( !(long)file1 ) return;
    
   FILE *file2 = fopen("new_2out_data.txt", "r");
   if ( !(long)file2 ) return;

  for ( int i = 0; i < n; i++ ) {
    fscanf( file1, "%f %E %E %E %E %E %E %E %E %E %E %E %E %E %E %E %E %E %E %E %E %E %E %E %E %E %E %E %E %E %E %E %E\n", &energy[i], &mean60[i], &rms60[i], &mean65[i], &rms65[i], &mean70[i], &rms70[i], &mean75[i], &rms75[i], &mean80[i], &rms80[i], &mean85[i], &rms85[i], &mean90[i], &rms90[i], &mean95[i], &rms95[i], &mean100[i], &rms100[i], &mean[i], &meanerror[i], &rms[i], &rmserror[i], &mean_mean[i], &rms_mean[i], &mean_meanerror[i], &rms_meanerror[i], &mean_sigma[i], &rms_sigma[i], &mean_sigmaerror[i], &rms_sigmaerror[i], &mean_chi[i], &rms_chi[i] );
    if ( feof( file1 ) ) break;
  }

  for ( int i = 0; i < n; i++ ) {
    fscanf( file2, "%f %E %E %E %E %E %E %E %E %E %E %E %E %E %E %E %E %E %E %E %E %E %E %E %E %E %E %E\n", &energy[i], &mean60[i], &rms60[i], &mean65[i], &rms65[i], &mean70[i], &rms70[i], &mean75[i], &rms75[i], &mean80[i], &rms80[i], &mean85[i], &rms85[i], &mean90[i], &rms90[i], &mean95[i], &rms95[i], &mean100[i], &rms100[i], &mean[i], &meanerror[i], &rms[i], &rmserror[i], &mean_mean2[i], &mean_meanerror2[i], &mean_sigma2[i], &mean_sigmaerror2[i], &mean_chi2[i] );
    if ( feof( file2 ) ) break;
  }
 
  for ( int i = 0; i < n; i++ ) {

    //linearity_error[ i ] = sqrt( ( pow( mean_meanerror[ i ], 2 ) ) + ( pow( rms_mean[ i ], 2 ) ) );
    //absolute_error[ i ] = sqrt( ( pow( mean_sigmaerror[ i ], 2 ) ) + ( pow( rms_sigma[ i ], 2 ) ) );
    //linearity_error2[ i ] = sqrt( ( pow( mean_meanerror2[ i ], 2 ) ) + ( pow( rms_mean2[ i ], 2 ) ) );
    //absolute_error2[ i ] = sqrt( ( pow( mean_sigmaerror2[ i ], 2 ) ) + ( pow( rms_sigma2[ i ], 2 ) ) );

    ratio_hist[ i ] = ( mean[i] - energy[i] ) / energy[i];
    ratio_error_stat_hist[ i ] = sqrt( pow( (meanerror[i]) / (energy[i]), 2 ) + pow( (mean[i] * energyerror[i]) / (energy[i] * energy[i]), 2 ) );
    ratio_error_sys_hist[ i ] = 0.0;
    ratio_error_hist[ i ] = sqrt( ( pow( ratio_error_stat_hist[ i ], 2 ) ) + ( pow( ratio_error_sys_hist[ i ], 2 ) ) );

    ratio60[ i ] = ( mean60[i] - energy[i] ) / energy[i];
    ratio_error_stat60[ i ] = 0.0;
    ratio_error_sys60[ i ] = 0.0;
    ratio_error60[ i ] = sqrt( ( pow( ratio_error_stat60[ i ], 2 ) ) + ( pow( ratio_error_sys60[ i ], 2 ) ) );
    ratio65[ i ] = ( mean65[i] - energy[i] ) / energy[i];
    ratio_error_stat65[ i ] = 0.0;
    ratio_error_sys65[ i ] = 0.0;
    ratio_error65[ i ] = sqrt( ( pow( ratio_error_stat65[ i ], 2 ) ) + ( pow( ratio_error_sys65[ i ], 2 ) ) );
    ratio70[ i ] = ( mean70[i] - energy[i] ) / energy[i];
    ratio_error_stat70[ i ] = 0.0;
    ratio_error_sys70[ i ] = 0.0;
    ratio_error70[ i ] = sqrt( ( pow( ratio_error_stat70[ i ], 2 ) ) + ( pow( ratio_error_sys70[ i ], 2 ) ) );
    ratio75[ i ] = ( mean75[i] - energy[i] ) / energy[i];
    ratio_error_stat75[ i ] = 0.0;
    ratio_error_sys75[ i ] = 0.0;
    ratio_error75[ i ] = sqrt( ( pow( ratio_error_stat75[ i ], 2 ) ) + ( pow( ratio_error_sys75[ i ], 2 ) ) );
    ratio80[ i ] = ( mean80[i] - energy[i] ) / energy[i];
    ratio_error_stat80[ i ] = 0.0;
    ratio_error_sys80[ i ] = 0.0;
    ratio_error80[ i ] = sqrt( ( pow( ratio_error_stat80[ i ], 2 ) ) + ( pow( ratio_error_sys80[ i ], 2 ) ) );
    ratio85[ i ] = ( mean85[i] - energy[i] ) / energy[i];
    ratio_error_stat85[ i ] = 0.0;
    ratio_error_sys85[ i ] = 0.0;
    ratio_error85[ i ] = sqrt( ( pow( ratio_error_stat85[ i ], 2 ) ) + ( pow( ratio_error_sys85[ i ], 2 ) ) );
    ratio90[ i ] = ( mean90[i] - energy[i] ) / energy[i];
    ratio_error_stat90[ i ] = 0.0;
    ratio_error_sys90[ i ] = 0.0;
    ratio_error90[ i ] = sqrt( ( pow( ratio_error_stat90[ i ], 2 ) ) + ( pow( ratio_error_sys90[ i ], 2 ) ) );
    ratio95[ i ] = ( mean95[i] - energy[i] ) / energy[i];
    ratio_error_stat95[ i ] = 0.0;
    ratio_error_sys95[ i ] = 0.0;
    ratio_error95[ i ] = sqrt( ( pow( ratio_error_stat95[ i ], 2 ) ) + ( pow( ratio_error_sys95[ i ], 2 ) ) );
    ratio100[ i ] = ( mean100[i] - energy[i] ) / energy[i];
    ratio_error_stat100[ i ] = 0.0;
    ratio_error_sys100[ i ] = 0.0;
    ratio_error100[ i ] = sqrt( ( pow( ratio_error_stat100[ i ], 2 ) ) + ( pow( ratio_error_sys100[ i ], 2 ) ) );

    ratio[ i ] = ( mean_mean[i] - energy[i] ) / energy[i];
    ratio_error_stat[ i ] = sqrt( pow( (mean_meanerror[i]) / (energy[i]), 2 ) + pow( (mean_mean[i] * energyerror[i]) / (energy[i] * energy[i]), 2 ) );
    ratio_error_sys[ i ] = sqrt( pow( (rms_mean[i]) / (energy[i]), 2 ) + pow( (mean_mean[i] * energyerror[i]) / (energy[i] * energy[i]), 2 ) );
    ratio_error[ i ] = sqrt( ( pow( ratio_error_stat[ i ], 2 ) ) + ( pow( ratio_error_sys[ i ], 2 ) ) );
    
    ratio2[ i ] = ( mean_mean2[i] - energy[i] ) / energy[i];
    ratio_error_stat2[ i ] = sqrt( pow( (mean_meanerror2[i]) / (energy[i]), 2 ) + pow( (mean_mean2[i] * energyerror[i]) / (energy[i] * energy[i]), 2 ) );
    ratio_error_sys2[ i ] = 0.0;
    ratio_error2[ i ] = sqrt( ( pow( ratio_error_stat2[ i ], 2 ) ) + ( pow( ratio_error_sys2[ i ], 2 ) ) );
    
    resolution_hist[ i ] = rms[i] / mean[i];
    resolution_error_stat_hist[ i ] = sqrt( pow( (rmserror[i]) / (mean[i]), 2 ) + pow( (rms[i] * meanerror[i]) / (mean[i] * mean[i]), 2 ) );
    resolution_error_sys_hist[ i ] = 0.0;
    resolution_error_hist[ i ] = sqrt( ( pow( resolution_error_stat_hist[ i ], 2 ) ) + ( pow( resolution_error_sys_hist[ i ], 2 ) ) );
    
    resolution60[ i ] = rms60[i] / mean60[i];
    resolution_error_stat60[ i ] = 0.0;
    resolution_error_sys60[ i ] = 0.0;
    resolution_error60[ i ] = sqrt( ( pow( resolution_error_stat60[ i ], 2 ) ) + ( pow( resolution_error_sys60[ i ], 2 ) ) );
    
    resolution65[ i ] = rms65[i] / mean65[i];
    resolution_error_stat65[ i ] = 0.0;
    resolution_error_sys65[ i ] = 0.0;
    resolution_error65[ i ] = sqrt( ( pow( resolution_error_stat65[ i ], 2 ) ) + ( pow( resolution_error_sys65[ i ], 2 ) ) );
    
    resolution70[ i ] = rms70[i] / mean70[i];
    resolution_error_stat70[ i ] = 0.0;
    resolution_error_sys70[ i ] = 0.0;
    resolution_error70[ i ] = sqrt( ( pow( resolution_error_stat70[ i ], 2 ) ) + ( pow( resolution_error_sys70[ i ], 2 ) ) );
    
    resolution75[ i ] = rms75[i] / mean75[i];
    resolution_error_stat75[ i ] = 0.0;
    resolution_error_sys75[ i ] = 0.0;
    resolution_error75[ i ] = sqrt( ( pow( resolution_error_stat75[ i ], 2 ) ) + ( pow( resolution_error_sys75[ i ], 2 ) ) );
    
    resolution80[ i ] = rms80[i] / mean80[i];
    resolution_error_stat80[ i ] = 0.0;
    resolution_error_sys80[ i ] = 0.0;
    resolution_error80[ i ] = sqrt( ( pow( resolution_error_stat80[ i ], 2 ) ) + ( pow( resolution_error_sys80[ i ], 2 ) ) );
    
    resolution85[ i ] = rms85[i] / mean85[i];
    resolution_error_stat85[ i ] = 0.0;
    resolution_error_sys85[ i ] = 0.0;
    resolution_error85[ i ] = sqrt( ( pow( resolution_error_stat85[ i ], 2 ) ) + ( pow( resolution_error_sys85[ i ], 2 ) ) );
    
    resolution90[ i ] = rms90[i] / mean90[i];
    resolution_error_stat90[ i ] = 0.0;
    resolution_error_sys90[ i ] = 0.0;
    resolution_error90[ i ] = sqrt( ( pow( resolution_error_stat90[ i ], 2 ) ) + ( pow( resolution_error_sys90[ i ], 2 ) ) );
    
    resolution95[ i ] = rms95[i] / mean95[i];
    resolution_error_stat95[ i ] = 0.0;
    resolution_error_sys95[ i ] = 0.0;
    resolution_error95[ i ] = sqrt( ( pow( resolution_error_stat95[ i ], 2 ) ) + ( pow( resolution_error_sys95[ i ], 2 ) ) );
    
    resolution100[ i ] = rms100[i] / mean100[i];
    resolution_error_stat100[ i ] = 0.0;
    resolution_error_sys100[ i ] = 0.0;
    resolution_error100[ i ] = sqrt( ( pow( resolution_error_stat100[ i ], 2 ) ) + ( pow( resolution_error_sys100[ i ], 2 ) ) );
    
    resolution[ i ] = mean_sigma[i] / mean_mean[i];
    resolution_error_stat[ i ] = sqrt( pow( (mean_sigmaerror[i]) / (mean_mean[i]), 2 ) + pow( (mean_sigma[i] * mean_meanerror[i]) / (mean_mean[i] * mean_mean[i]), 2 ) );
    resolution_error_sys[ i ] = sqrt( pow( (rms_sigma[i]) / (mean_mean[i]), 2 ) + pow( (mean_sigma[i] * rms_mean[i]) / (mean_mean[i] * mean_mean[i]), 2 ) );
    resolution_error[ i ] = sqrt( ( pow( resolution_error_stat[ i ], 2 ) ) + ( pow( resolution_error_sys[ i ], 2 ) ) );

    resolution2[ i ] = mean_sigma2[i] / mean_mean2[i];
    resolution_error_stat2[ i ] = sqrt( pow( (mean_sigmaerror2[i]) / (mean_mean2[i]), 2 ) + pow( (mean_sigma2[i] * mean_meanerror2[i]) / (mean_mean2[i] * mean_mean2[i]), 2 ) );
    resolution_error_sys2[ i ] = 0.0;
    resolution_error2[ i ] = sqrt( ( pow( resolution_error_stat2[ i ], 2 ) ) + ( pow( resolution_error_sys2[ i ], 2 ) ) );
    
  }
    
   printf( "\n" );
   for (int i = 0; i < n; i++) {
     printf( " %f ", energy[i] );
     printf( " %f ", energyerror[i] );
     
     printf( " %f ", mean[i] );
     printf( " %f ", meanerror[i] );
     printf( " %f ", rms[i] );
     printf( " %f ", rmserror[i] );

     printf( " %f ", mean60[i] );
     printf( " %f ", rms60[i] );
     printf( " %f ", mean65[i] );
     printf( " %f ", rms65[i] );
     printf( " %f ", mean70[i] );
     printf( " %f ", rms70[i] );
     printf( " %f ", mean75[i] );
     printf( " %f ", rms75[i] );
     printf( " %f ", mean80[i] );
     printf( " %f ", rms80[i] );
     printf( " %f ", mean85[i] );
     printf( " %f ", rms85[i] );
     printf( " %f ", mean90[i] );
     printf( " %f ", rms90[i] );
     printf( " %f ", mean95[i] );
     printf( " %f ", rms95[i] );
     printf( " %f ", mean100[i] );
     printf( " %f ", rms100[i] );
       
     printf( " %f ", ratio_hist[i] );
     printf( " %f ", ratio_error_hist[i] );
     printf( " %f ", resolution_hist[i] );
     printf( " %f ", resolution_error_hist[i] );
     
     printf( " %f ", ratio60[i] );
     printf( " %f ", ratio_error60[i] );
     printf( " %f ", resolution60[i] );
     printf( " %f ", resolution_error60[i] );
     printf( " %f ", ratio65[i] );
     printf( " %f ", ratio_error65[i] );
     printf( " %f ", resolution65[i] );
     printf( " %f ", resolution_error65[i] );
     printf( " %f ", ratio70[i] );
     printf( " %f ", ratio_error70[i] );
     printf( " %f ", resolution70[i] );
     printf( " %f ", resolution_error70[i] );
     printf( " %f ", ratio75[i] );
     printf( " %f ", ratio_error75[i] );
     printf( " %f ", resolution75[i] );
     printf( " %f ", resolution_error75[i] );
     printf( " %f ", ratio80[i] );
     printf( " %f ", ratio_error80[i] );
     printf( " %f ", resolution80[i] );
     printf( " %f ", resolution_error80[i] );
     printf( " %f ", ratio85[i] );
     printf( " %f ", ratio_error85[i] );
     printf( " %f ", resolution85[i] );
     printf( " %f ", resolution_error85[i] );
     printf( " %f ", ratio90[i] );
     printf( " %f ", ratio_error90[i] );
     printf( " %f ", resolution90[i] );
     printf( " %f ", resolution_error90[i] );
     printf( " %f ", ratio95[i] );
     printf( " %f ", ratio_error95[i] );
     printf( " %f ", resolution95[i] );
     printf( " %f ", resolution_error95[i] );
     printf( " %f ", ratio100[i] );
     printf( " %f ", ratio_error100 [i] );
     printf( " %f ", resolution100[i] );
     printf( " %f ", resolution_error100[i] );
     
     printf( " %f ", mean_mean[i] );
     printf( " %f ", rms_mean[i] );
     printf( " %f ", mean_meanerror[i] );
     printf( " %f ", rms_meanerror[i] );
     printf( " %f ", mean_sigma[i] );
     printf( " %f ", rms_sigma[i] );
     printf( " %f ", mean_sigmaerror[i] );
     printf( " %f ", rms_sigmaerror[i] );
     printf( " %f ", linearity_error[i] );
     printf( " %f ", absolute_error[i] );
     printf( " %f ", ratio[i] );
     printf( " %f ", ratio_error[i] );
     printf( " %f ", resolution[i] );
     printf( " %f ", resolution_error[i] );
     
     printf( " %f ", mean_mean2[i] );
     printf( " %f ", rms_mean2[i] );
     printf( " %f ", mean_meanerror2[i] );
     printf( " %f ", rms_meanerror2[i] );
     printf( " %f ", mean_sigma2[i] );
     printf( " %f ", rms_sigma2[i] );
     printf( " %f ", mean_sigmaerror2[i] );
     printf( " %f ", rms_sigmaerror2[i] );
     printf( " %f ", linearity_error2[i] );
     printf( " %f ", absolute_error2[i] );
     printf( " %f ", ratio2[i] );
     printf( " %f ", ratio_error2[i] );
     printf( " %f ", resolution2[i] );
     printf( " %f ", resolution_error2[i] );
     
     printf( "\n" );
     printf( "\n" );
     printf( "\n" );

   }

   TGraphErrors *agr;
   TGraphErrors *bgr;
    
   TGraphErrors *cgr;
   TGraphErrors *dgr;
    
   TGraphErrors *egr;
   TGraphErrors *fgr;

   char fname[ 100 ];
   for ( int i = 0; i < 100; i++ ) fname[ i ] = 0;

   c1->cd();
   agr = new TGraphErrors( n, energy, ratio80, energyerror, ratio_error_sys80 );
   //agr = new TGraphErrors( n, energy, ratio90, energyerror, ratio_error_sys90 );
   //agr = new TGraphErrors( n, energy, ratio, energyerror, ratio_error_sys );
   //agr = new TGraphErrors( n, energy, ratio90, energyerror, ratio_error_sys90 );
   //agr = new TGraphErrors( n, energy, ratio2, energyerror, ratio_error_sys2 );
   //agr = new TGraphErrors( n, energy, ratio, energyerror, ratio_error_sys );
   agr->GetYaxis()->SetTitle("( E_{reco} - E_{true} ) / E_{true}");
   agr->GetXaxis()->SetTitle("E_{true}, GeV");
   bgr = new TGraphErrors( n, energy, ratio80, energyerror, ratio_error_stat80 );
   //bgr = new TGraphErrors( n, energy, ratio90, energyerror, ratio_error_stat90 );
   //bgr = new TGraphErrors( n, energy, ratio, energyerror, ratio_error_stat );
   //bgr = new TGraphErrors( n, energy, ratio90, energyerror, ratio_error_stat90 );
   //bgr = new TGraphErrors( n, energy, ratio2, energyerror, ratio_error_stat2 );
   //bgr = new TGraphErrors( n, energy, ratio, energyerror, ratio_error_stat );
   bgr->GetYaxis()->SetTitle("( E_{reco} - E_{true} ) / E_{true}");
   bgr->GetXaxis()->SetTitle("E_{true}, GeV");
   cgr = new TGraphErrors( n, energy, ratio85, energyerror, ratio_error_sys85 );
   //cgr = new TGraphErrors( n, energy, ratio95, energyerror, ratio_error_sys95 );
   //cgr = new TGraphErrors( n, energy, ratio2, energyerror, ratio_error_sys2 );
   //cgr = new TGraphErrors( n, energy, ratio100, energyerror, ratio_error_sys100 );
   //cgr = new TGraphErrors( n, energy, ratio_hist, energyerror, ratio_error_sys_hist );
   //cgr = new TGraphErrors( n, energy, ratio2, energyerror, ratio_error_sys2 );
   cgr->GetYaxis()->SetTitle("( E_{reco} - E_{true} ) / E_{true}");
   cgr->GetXaxis()->SetTitle("E_{true}, GeV");
   dgr = new TGraphErrors( n, energy, ratio85, energyerror, ratio_error_stat85 );
   //dgr = new TGraphErrors( n, energy, ratio95, energyerror, ratio_error_stat95 );
   //dgr = new TGraphErrors( n, energy, ratio2, energyerror, ratio_error_stat2 );
   //dgr = new TGraphErrors( n, energy, ratio100, energyerror, ratio_error_stat100 );
   //dgr = new TGraphErrors( n, energy, ratio_hist, energyerror, ratio_error_stat_hist );
   //dgr = new TGraphErrors( n, energy, ratio2, energyerror, ratio_error_stat2 );
   dgr->GetYaxis()->SetTitle("( E_{reco} - E_{true} ) / E_{true}");
   dgr->GetXaxis()->SetTitle("E_{true}, GeV");
   egr = new TGraphErrors( n, energy, ratio90, energyerror, ratio_error_sys90 );
   //egr = new TGraphErrors( n, energy, ratio100, energyerror, ratio_error_sys100 );
   //egr = new TGraphErrors( n, energy, ratio90, energyerror, ratio_error_sys90 );
   //egr = new TGraphErrors( n, energy, ratio_hist, energyerror, ratio_error_sys_hist );
   //egr = new TGraphErrors( n, energy, ratio90, energyerror, ratio_error_sys90 );
   //egr = new TGraphErrors( n, energy, ratio_hist, energyerror, ratio_error_sys_hist );
   egr->GetYaxis()->SetTitle("( E_{reco} - E_{true} ) / E_{true}");
   egr->GetXaxis()->SetTitle("E_{true}, GeV");
   fgr = new TGraphErrors( n, energy, ratio90, energyerror, ratio_error_stat90 );
   //fgr = new TGraphErrors( n, energy, ratio100, energyerror, ratio_error_stat100 );
   //fgr = new TGraphErrors( n, energy, ratio90, energyerror, ratio_error_stat90 );
   //fgr = new TGraphErrors( n, energy, ratio_hist, energyerror, ratio_error_stat_hist );
   //fgr = new TGraphErrors( n, energy, ratio90, energyerror, ratio_error_stat90 );
   //fgr = new TGraphErrors( n, energy, ratio_hist, energyerror, ratio_error_stat_hist );
   fgr->GetYaxis()->SetTitle("( E_{reco} - E_{true} ) / E_{true}");
   fgr->GetXaxis()->SetTitle("E_{true}, GeV");
   sprintf( fname, "Linearity" );
   agr->GetYaxis()->SetRangeUser(-0.2, 0.2);
   agr->SetTitle(fname);

   agr->SetFillColor(kCyan);
   agr->SetFillStyle(3001);
   agr->SetMarkerColor(kCyan);
   agr->SetLineColor(kCyan);
   agr->SetLineWidth(3);
   agr->SetMarkerStyle(34);
   agr->Draw("A 3");
   bgr->SetMarkerColor(kBlue);
   bgr->SetLineColor(kBlue);
   bgr->SetLineWidth(3);
   bgr->SetFillColor(kCyan);
   bgr->SetMarkerStyle(20);
   bgr->Draw("P SAME");
   cgr->SetMarkerColor(kYellow-6);
   cgr->SetFillStyle(3001);
   cgr->SetLineColor(kYellow-6);
   cgr->SetLineWidth(3);
   cgr->SetFillColor(kYellow-6);
   cgr->SetMarkerStyle(20);
   cgr->Draw("3 SAME");
   dgr->SetMarkerColor(kRed);
   dgr->SetLineColor(kRed);
   dgr->SetLineWidth(3);
   dgr->SetFillColor(kYellow-6);
   dgr->SetMarkerStyle(20);
   dgr->Draw("P SAME");
   egr->SetMarkerColor(kViolet-6);
   egr->SetFillStyle(3001);
   egr->SetLineColor(kViolet-6);
   egr->SetLineWidth(3);
   egr->SetFillColor(kViolet-6);
   egr->SetMarkerStyle(20);
   egr->Draw("3 SAME");
   fgr->SetMarkerColor(kGreen+1);
   fgr->SetLineColor(kGreen+1);
   fgr->SetLineWidth(3);
   fgr->SetFillColor(kViolet-6);
   fgr->SetMarkerStyle(20);
   fgr->Draw("P SAME");
    
   c1->Update();

   c2->cd();
   agr = new TGraphErrors( n, energy, rms80, energyerror, energyerror );
   //agr = new TGraphErrors( n, energy, rms90, energyerror, energyerror );
   //agr = new TGraphErrors( n, energy, mean_sigma, energyerror, rms_sigma );
   //agr = new TGraphErrors( n, energy, rms90, energyerror, energyerror );
   //agr = new TGraphErrors( n, energy, mean_sigma2, energyerror, rms_sigma2 );
   //agr = new TGraphErrors( n, energy, mean_sigma, energyerror, rms_sigma );
   agr->GetYaxis()->SetTitle("#sigma_{reco}, GeV");
   agr->GetXaxis()->SetTitle("E_{true}, GeV");
   bgr = new TGraphErrors( n, energy, rms80, energyerror, energyerror );
   //bgr = new TGraphErrors( n, energy, rms90, energyerror, energyerror );
   //bgr = new TGraphErrors( n, energy, mean_sigma, energyerror, mean_sigmaerror );
   //bgr = new TGraphErrors( n, energy, rms90, energyerror, energyerror );
   //bgr = new TGraphErrors( n, energy, mean_sigma2, energyerror, mean_sigmaerror2 );
   //bgr = new TGraphErrors( n, energy, mean_sigma, energyerror, mean_sigmaerror );
   bgr->GetYaxis()->SetTitle("#sigma_{reco}, GeV");
   bgr->GetXaxis()->SetTitle("E_{true}, GeV");
   cgr = new TGraphErrors( n, energy, rms85, energyerror, energyerror );
   //cgr = new TGraphErrors( n, energy, rms95, energyerror, energyerror );
   //cgr = new TGraphErrors( n, energy, mean_sigma2, energyerror, rms_sigma2 );
   //cgr = new TGraphErrors( n, energy, rms100, energyerror, energyerror );
   //cgr = new TGraphErrors( n, energy, rms, energyerror, energyerror );// energyerror == 0
   //cgr = new TGraphErrors( n, energy, mean_sigma2, energyerror, rms_sigma2 );
   cgr->GetYaxis()->SetTitle("#sigma_{reco}, GeV");
   cgr->GetXaxis()->SetTitle("E_{true}, GeV");
   dgr = new TGraphErrors( n, energy, rms85, energyerror, energyerror );
   //dgr = new TGraphErrors( n, energy, rms95, energyerror, energyerror );
   //dgr = new TGraphErrors( n, energy, mean_sigma2, energyerror, mean_sigmaerror2 );
   //dgr = new TGraphErrors( n, energy, rms100, energyerror, energyerror );
   //dgr = new TGraphErrors( n, energy, rms, energyerror, rmserror );
   //dgr = new TGraphErrors( n, energy, mean_sigma2, energyerror, mean_sigmaerror2 );
   dgr->GetYaxis()->SetTitle("#sigma_{reco}, GeV");
   dgr->GetXaxis()->SetTitle("E_{true}, GeV");
   egr = new TGraphErrors( n, energy, rms90, energyerror, energyerror );
   //egr = new TGraphErrors( n, energy, rms100, energyerror, energyerror );
   //egr = new TGraphErrors( n, energy, rms90, energyerror, energyerror );
   //egr = new TGraphErrors( n, energy, rms, energyerror, energyerror );
   //egr = new TGraphErrors( n, energy, rms90, energyerror, energyerror );
   //egr = new TGraphErrors( n, energy, rms, energyerror, energyerror );
   egr->GetYaxis()->SetTitle("#sigma_{reco}, GeV");
   egr->GetXaxis()->SetTitle("E_{true}, GeV");
   fgr = new TGraphErrors( n, energy, rms90, energyerror, energyerror );
   //fgr = new TGraphErrors( n, energy, rms100, energyerror, energyerror );
   //fgr = new TGraphErrors( n, energy, rms90, energyerror, energyerror );
   //fgr = new TGraphErrors( n, energy, rms, energyerror, rmserror );
   //fgr = new TGraphErrors( n, energy, rms90, energyerror, energyerror );
   //fgr = new TGraphErrors( n, energy, rms, energyerror, rmserror );
   fgr->GetYaxis()->SetTitle("#sigma_{reco}, GeV");
   fgr->GetXaxis()->SetTitle("E_{true}, GeV");
   sprintf( fname, "Absolute energy resolution" );
   agr->GetYaxis()->SetRangeUser(0.0, 9.0);
   agr->SetTitle(fname);

   agr->SetFillColor(kCyan);
   agr->SetFillStyle(3001);
   agr->SetMarkerColor(kCyan);
   agr->SetLineColor(kCyan);
   agr->SetLineWidth(3);
   agr->SetMarkerStyle(34);
   agr->Draw("A 3");
   bgr->SetMarkerColor(kBlue);
   bgr->SetLineColor(kBlue);
   bgr->SetLineWidth(3);
   bgr->SetFillColor(kCyan);
   bgr->SetMarkerStyle(20);
   bgr->Draw("P SAME");
   cgr->SetMarkerColor(kYellow-6);
   cgr->SetFillStyle(3001);
   cgr->SetLineColor(kYellow-6);
   cgr->SetLineWidth(3);
   cgr->SetFillColor(kYellow-6);
   cgr->SetMarkerStyle(20);
   cgr->Draw("3 SAME");
   dgr->SetMarkerColor(kRed);
   dgr->SetLineColor(kRed);
   dgr->SetLineWidth(3);
   dgr->SetFillColor(kYellow-6);
   dgr->SetMarkerStyle(20);
   dgr->Draw("P SAME");
   egr->SetMarkerColor(kViolet-6);
   egr->SetFillStyle(3001);
   egr->SetLineColor(kViolet-6);
   egr->SetLineWidth(3);
   egr->SetFillColor(kViolet-6);
   egr->SetMarkerStyle(20);
   egr->Draw("3 SAME");
   fgr->SetMarkerColor(kGreen+1);
   fgr->SetLineColor(kGreen+1);
   fgr->SetLineWidth(3);
   fgr->SetFillColor(kViolet-6);
   fgr->SetMarkerStyle(20);
   fgr->Draw("P SAME");
   c2->Update();

   c3->cd();
   agr = new TGraphErrors( n, energy, mean80, energyerror, energyerror );
   //agr = new TGraphErrors( n, energy, mean90, energyerror, energyerror );
   //agr = new TGraphErrors( n, energy, mean_mean, energyerror, rms_mean );
   //agr = new TGraphErrors( n, energy, mean90, energyerror, energyerror );
   //agr = new TGraphErrors( n, energy, mean_mean2, energyerror, rms_mean2 );
   //agr = new TGraphErrors( n, energy, mean_mean, energyerror, rms_mean );
   agr->GetYaxis()->SetTitle("E_{reco}, GeV");
   agr->GetXaxis()->SetTitle("E_{true}, GeV");
   bgr = new TGraphErrors( n, energy, mean80, energyerror, energyerror );
   //bgr = new TGraphErrors( n, energy, mean90, energyerror, energyerror );
   //bgr = new TGraphErrors( n, energy, mean_mean, energyerror, mean_meanerror );
   //bgr = new TGraphErrors( n, energy, mean90, energyerror, energyerror );
   //bgr = new TGraphErrors( n, energy, mean_mean2, energyerror, mean_meanerror2 );
   //bgr = new TGraphErrors( n, energy, mean_mean, energyerror, mean_meanerror );
   bgr->GetYaxis()->SetTitle("E_{reco}, GeV");
   bgr->GetXaxis()->SetTitle("E_{true}, GeV");
   cgr = new TGraphErrors( n, energy, mean85, energyerror, energyerror );
   //cgr = new TGraphErrors( n, energy, mean95, energyerror, energyerror );
   //cgr = new TGraphErrors( n, energy, mean_mean2, energyerror, rms_mean2 );
   //cgr = new TGraphErrors( n, energy, mean100, energyerror, energyerror );
   //cgr = new TGraphErrors( n, energy, mean, energyerror, energyerror );
   //cgr = new TGraphErrors( n, energy, mean_mean2, energyerror, rms_mean2 );
   cgr->GetYaxis()->SetTitle("E_{reco}, GeV");
   cgr->GetXaxis()->SetTitle("E_{true}, GeV");
   dgr = new TGraphErrors( n, energy, mean85, energyerror, energyerror );
   //dgr = new TGraphErrors( n, energy, mean95, energyerror, energyerror );
   //dgr = new TGraphErrors( n, energy, mean_mean2, energyerror, mean_meanerror2 );
   //dgr = new TGraphErrors( n, energy, mean100, energyerror, energyerror );
   //dgr = new TGraphErrors( n, energy, mean, energyerror, meanerror );
   //dgr = new TGraphErrors( n, energy, mean_mean2, energyerror, mean_meanerror2 );
   dgr->GetYaxis()->SetTitle("E_{reco}, GeV");
   dgr->GetXaxis()->SetTitle("E_{true}, GeV");
   egr = new TGraphErrors( n, energy, mean90, energyerror, energyerror );
   //egr = new TGraphErrors( n, energy, mean100, energyerror, energyerror );
   //egr = new TGraphErrors( n, energy, mean90, energyerror, energyerror );
   //egr = new TGraphErrors( n, energy, mean, energyerror, energyerror );
   //egr = new TGraphErrors( n, energy, mean90, energyerror, energyerror );
   //egr = new TGraphErrors( n, energy, mean, energyerror, energyerror );
   egr->GetYaxis()->SetTitle("E_{reco}, GeV");
   egr->GetXaxis()->SetTitle("E_{true}, GeV");
   fgr = new TGraphErrors( n, energy, mean90, energyerror, energyerror );
   //fgr = new TGraphErrors( n, energy, mean100, energyerror, energyerror );
   //fgr = new TGraphErrors( n, energy, mean90, energyerror, energyerror );
   //fgr = new TGraphErrors( n, energy, mean, energyerror, meanerror );
   //fgr = new TGraphErrors( n, energy, mean90, energyerror, energyerror );
   //fgr = new TGraphErrors( n, energy, mean, energyerror, meanerror );
   fgr->GetYaxis()->SetTitle("E_{reco}, GeV");
   fgr->GetXaxis()->SetTitle("E_{true}, GeV");
   sprintf( fname, "Linearity 2" );
   agr->GetYaxis()->SetRangeUser(0.0, 70.0);
   agr->SetTitle(fname);

   agr->SetFillColor(kCyan);
   agr->SetFillStyle(3001);
   agr->SetMarkerColor(kCyan);
   agr->SetLineColor(kCyan);
   agr->SetLineWidth(3);
   agr->SetMarkerStyle(34);
   agr->Draw("A 3");
   bgr->SetMarkerColor(kBlue);
   bgr->SetLineColor(kBlue);
   bgr->SetLineWidth(3);
   bgr->SetFillColor(kCyan);
   bgr->SetMarkerStyle(20);
   bgr->Draw("P SAME");
   cgr->SetMarkerColor(kYellow-6);
   cgr->SetFillStyle(3001);
   cgr->SetLineColor(kYellow-6);
   cgr->SetLineWidth(3);
   cgr->SetFillColor(kYellow-6);
   cgr->SetMarkerStyle(20);
   cgr->Draw("3 SAME");
   dgr->SetMarkerColor(kRed);
   dgr->SetLineColor(kRed);
   dgr->SetLineWidth(3);
   dgr->SetFillColor(kYellow-6);
   dgr->SetMarkerStyle(20);
   dgr->Draw("P SAME");
   egr->SetMarkerColor(kViolet-6);
   egr->SetFillStyle(3001);
   egr->SetLineColor(kViolet-6);
   egr->SetLineWidth(3);
   egr->SetFillColor(kViolet-6);
   egr->SetMarkerStyle(20);
   egr->Draw("3 SAME");
   fgr->SetMarkerColor(kGreen+1);
   fgr->SetLineColor(kGreen+1);
   fgr->SetLineWidth(3);
   fgr->SetFillColor(kViolet-6);
   fgr->SetMarkerStyle(20);
   fgr->Draw("P SAME");
   c3->Update();

   c4->cd();
   agr = new TGraphErrors( n, energy, resolution80, energyerror, resolution_error_sys80 );
   //agr = new TGraphErrors( n, energy, resolution90, energyerror, resolution_error_sys90 );
   //agr = new TGraphErrors( n, energy, resolution, energyerror, resolution_error_sys );
   //agr = new TGraphErrors( n, energy, resolution90, energyerror, resolution_error_sys90 );
   //agr = new TGraphErrors( n, energy, resolution2, energyerror, resolution_error_sys2 );
   //agr = new TGraphErrors( n, energy, resolution, energyerror, resolution_error_sys );
   agr->GetYaxis()->SetTitle("#sigma_{reco} / E_{reco}");
   agr->GetXaxis()->SetTitle("E_{true}, GeV");
   bgr = new TGraphErrors( n, energy, resolution80, energyerror, resolution_error_stat80 );
   //bgr = new TGraphErrors( n, energy, resolution90, energyerror, resolution_error_stat90 );
   //bgr = new TGraphErrors( n, energy, resolution, energyerror, resolution_error_stat );
   //bgr = new TGraphErrors( n, energy, resolution90, energyerror, resolution_error_stat90 );
   //bgr = new TGraphErrors( n, energy, resolution2, energyerror, resolution_error_stat2 );
   //bgr = new TGraphErrors( n, energy, resolution, energyerror, resolution_error_stat );
   bgr->GetYaxis()->SetTitle("#sigma_{reco} / E_{reco}");
   bgr->GetXaxis()->SetTitle("E_{true}, GeV");
   cgr = new TGraphErrors( n, energy, resolution85, energyerror, resolution_error_sys85 );
   //cgr = new TGraphErrors( n, energy, resolution95, energyerror, resolution_error_sys95 );
   //cgr = new TGraphErrors( n, energy, resolution2, energyerror, resolution_error_sys2 );
   //cgr = new TGraphErrors( n, energy, resolution100, energyerror, resolution_error_sys100 );
   //cgr = new TGraphErrors( n, energy, resolution_hist, energyerror, resolution_error_sys_hist );
   //cgr = new TGraphErrors( n, energy, resolution2, energyerror, resolution_error_sys2 );
   cgr->GetYaxis()->SetTitle("#sigma_{reco} / E_{reco}");
   cgr->GetXaxis()->SetTitle("E_{true}, GeV");
   dgr = new TGraphErrors( n, energy, resolution85, energyerror, resolution_error_stat85 );
   //dgr = new TGraphErrors( n, energy, resolution95, energyerror, resolution_error_stat95 );
   //dgr = new TGraphErrors( n, energy, resolution2, energyerror, resolution_error_stat2 );
   //dgr = new TGraphErrors( n, energy, resolution100, energyerror, resolution_error_stat100 );
   //dgr = new TGraphErrors( n, energy, resolution_hist, energyerror, resolution_error_stat_hist );
   //dgr = new TGraphErrors( n, energy, resolution2, energyerror, resolution_error_stat2 );
   dgr->GetYaxis()->SetTitle("#sigma_{reco} / E_{reco}");
   dgr->GetXaxis()->SetTitle("E_{true}, GeV");
   egr = new TGraphErrors( n, energy, resolution90, energyerror, resolution_error_sys90 );
   //egr = new TGraphErrors( n, energy, resolution100, energyerror, resolution_error_sys100 );
   //egr = new TGraphErrors( n, energy, resolution90, energyerror, resolution_error_sys90 );
   //egr = new TGraphErrors( n, energy, resolution_hist, energyerror, resolution_error_sys_hist );
   //egr = new TGraphErrors( n, energy, resolution90, energyerror, resolution_error_sys90 );
   //egr = new TGraphErrors( n, energy, resolution_hist, energyerror, resolution_error_sys_hist );
   egr->GetYaxis()->SetTitle("#sigma_{reco} / E_{reco}");
   egr->GetXaxis()->SetTitle("E_{true}, GeV");
   fgr = new TGraphErrors( n, energy, resolution90, energyerror, resolution_error_stat90 );
   //fgr = new TGraphErrors( n, energy, resolution100, energyerror, resolution_error_stat100 );
   //fgr = new TGraphErrors( n, energy, resolution90, energyerror, resolution_error_stat90 );
   //fgr = new TGraphErrors( n, energy, resolution_hist, energyerror, resolution_error_stat_hist );
   //fgr = new TGraphErrors( n, energy, resolution90, energyerror, resolution_error_stat90 );
   //fgr = new TGraphErrors( n, energy, resolution_hist, energyerror, resolution_error_stat_hist );
   fgr->GetYaxis()->SetTitle("#sigma_{reco} / E_{reco}");
   fgr->GetXaxis()->SetTitle("E_{true}, GeV");
   sprintf( fname, "Relative energy resolution" );
   agr->GetYaxis()->SetRangeUser(0.0, 0.30);
   agr->SetTitle(fname);

   agr->SetFillColor(kCyan);
   agr->SetFillStyle(3001);
   agr->SetMarkerColor(kCyan);
   agr->SetLineColor(kCyan);
   agr->SetLineWidth(3);
   agr->SetMarkerStyle(34);
   agr->Draw("A 3");
   bgr->SetMarkerColor(kBlue);
   bgr->SetLineColor(kBlue);
   bgr->SetLineWidth(3);
   bgr->SetFillColor(kCyan);
   bgr->SetMarkerStyle(20);
   bgr->Draw("P SAME");
   cgr->SetMarkerColor(kYellow-6);
   cgr->SetFillStyle(3001);
   cgr->SetLineColor(kYellow-6);
   cgr->SetLineWidth(3);
   cgr->SetFillColor(kYellow-6);
   cgr->SetMarkerStyle(20);
   cgr->Draw("3 SAME");
   dgr->SetMarkerColor(kRed);
   dgr->SetLineColor(kRed);
   dgr->SetLineWidth(3);
   dgr->SetFillColor(kYellow-6);
   dgr->SetMarkerStyle(20);
   dgr->Draw("P SAME");
   egr->SetMarkerColor(kViolet-6);
   egr->SetFillStyle(3001);
   egr->SetLineColor(kViolet-6);
   egr->SetLineWidth(3);
   egr->SetFillColor(kViolet-6);
   egr->SetMarkerStyle(20);
   egr->Draw("3 SAME");
   fgr->SetMarkerColor(kGreen+1);
   fgr->SetLineColor(kGreen+1);
   fgr->SetLineWidth(3);
   fgr->SetFillColor(kViolet-6);
   fgr->SetMarkerStyle(20);
   fgr->Draw("P SAME");
   c4->Update();
    
   TLegend *lsc1 = new TLegend(0.55,0.62,0.90,0.92);
   lsc1->AddEntry(bgr,"data, rms80 w/o errors","plf");
   lsc1->AddEntry(dgr,"data, rms85 w/o errors","plf");
   lsc1->AddEntry(fgr,"data, rms90 w/o errors","plf");
   //lsc1->AddEntry(bgr,"data, rms90 w/o errors","plf");
   //lsc1->AddEntry(dgr,"data, rms95 w/o errors","plf");
   //lsc1->AddEntry(fgr,"data, rms100 w/o errors","plf");
   //lsc1->AddEntry(bgr,"data, fit 1","plf");
   //lsc1->AddEntry(dgr,"data, fit 2 (stat)","plf");
   //lsc1->AddEntry(fgr,"data, rms90 w/o errors","plf");
   //lsc1->AddEntry(bgr,"data, rms90 w/o errors","plf");
   //lsc1->AddEntry(dgr,"data, rms100 w/o errors","plf");
   //lsc1->AddEntry(fgr,"data, rms_hist (stat)","plf");
   //lsc1->AddEntry(bgr,"data, fit 2 (stat)","plf");
   //lsc1->AddEntry(dgr,"data, rms_hist (stat)","plf");
   //lsc1->AddEntry(fgr,"data, rms90 w/o errors","plf");
   //lsc1->AddEntry(bgr,"data, fit 1","plf");
   //lsc1->AddEntry(dgr,"data, fit 2 (stat)","plf");
   //lsc1->AddEntry(fgr,"data, rms_hist (stat)","plf");
    
   TLegend *lsc2 = new TLegend(0.55,0.62,0.90,0.92);
   lsc2->AddEntry(bgr,"data, rms80 w/o errors","plf");
   lsc2->AddEntry(dgr,"data, rms85 w/o errors","plf");
   lsc2->AddEntry(fgr,"data, rms90 w/o errors","plf");
    
   TLegend *lsc3 = new TLegend(0.55,0.62,0.90,0.92);
   lsc3->AddEntry(bgr,"data, rms80 w/o errors","plf");
   lsc3->AddEntry(dgr,"data, rms85 w/o errors","plf");
   lsc3->AddEntry(fgr,"data, rms90 w/o errors","plf");
    
   TLegend *lsc4 = new TLegend(0.55,0.62,0.90,0.92);
   lsc4->AddEntry(bgr,"data, rms80 w/o errors","plf");
   lsc4->AddEntry(dgr,"data, rms85 w/o errors","plf");
   lsc4->AddEntry(fgr,"data, rms90 w/o errors","plf");

   c1->cd();
   lsc1->Draw();
   c2->cd();
   lsc2->Draw();
   c3->cd();
   lsc3->Draw();
   c4->cd();
   lsc4->Draw();

}
